version: "3.8"
services:
  fundamentos-php:
    build: .
    container_name: fundamentos-php
    ports:
      - "80:80"
      - "443:443"
    volumes: 
        - ./:/var/www/html/
    networks: 
      - ecommerce

networks:
  ecommerce:
    external: true